image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .venv
    - .cache/pip/
    
before_script:
  - pip install poetry
  - pip install pytest
  - poetry config virtualenvs.in-project true
  - poetry install
#  - .venv/bin/python setup.py install

tests:
  stage: tests
  script: poetry run python -m pytest  --junitxml=junit.xml
  artifacts:
    reports:
      junit: junit.xml


check:
  stage: check
  script: 
    - poetry run python setup.py check -ms
#    - .venv/bin/pylanguagetool --help

sdist:
  stage: build
  script: poetry run python setup.py sdist
  artifacts:
    name: sdist
    paths:
      - dist


bdist:
  stage: build
  script: poetry run python setup.py bdist_wheel
  artifacts:
    name: bdist
    paths:
      - dist


docs:
  stage: docs
  script:
    - poetry run python setup.py build_sphinx -W -b dirhtml
#    - .venv/bin/pylanguagetool --pwl spelling.txt --disabled-rules=WHITESPACE_RULE README.rst
  artifacts:
    name: docs
    paths:
      - docs/_build/

deploy_docs:
  stage: deploy
  tags:
    - shell
  script: 
    - cp -r docs/_build/dirhtml /var/www/pylanguagetool/

stages:
  - check
  - tests
  - build
  - docs
  - deploy

