language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5-7.0"
# command to install dependencies
before_install:
  - pip install poetry
  - pip install markdown2
  - pip install beautifulsoup4
install:
  - poetry install
# command to run tests
script:
  - python -m pytest
  - python setup.py check -ms
  - python setup.py build_sphinx -W -b dirhtml
  - pylanguagetool --pwl spelling.txt --disabled-rules=WHITESPACE_RULE README.rst
